
package com.totyu.apps.ws.tzsb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.totyu.apps.ws.WsException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "TzsbWebService", targetNamespace = "http://ws.web.totyu.com")
public interface TzsbService {


    /**
     * 
     * @param businessCode
     * @param inputXML
     * @param operationCode
     * @return
     *     returns java.lang.String
     * @throws WsException_Exception
     */
    @WebMethod
    @WebResult(name = "outputXML", targetNamespace = "")
    @RequestWrapper(localName = "tzsbTranService", targetNamespace = "http://ws.web.totyu.com")
    @ResponseWrapper(localName = "tzsbTranServiceResponse", targetNamespace = "http://ws.web.totyu.com")
    public String tzsbTranService(
        @WebParam(name = "businessCode", targetNamespace = "")
        String businessCode,
        @WebParam(name = "operationCode", targetNamespace = "")
        String operationCode,
        @WebParam(name = "inputXML", targetNamespace = "")
        String inputXML)
        throws WsException
    ;

}
