
package com.lejingw.apps.ws31;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "Hello3WsException", targetNamespace = "http://ws3.apps.lejingw.com")
public class Hello3WsException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private Hello3WsException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public Hello3WsException_Exception(String message, Hello3WsException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public Hello3WsException_Exception(String message, Hello3WsException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.lejingw.apps.ws31.Hello3WsException
     */
    public Hello3WsException getFaultInfo() {
        return faultInfo;
    }

}
