
package com.lejingw.apps.ws31;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "Hello3WsService", targetNamespace = "http://ws3.apps.lejingw.com", wsdlLocation = "http://localhost:8080/lstzsb/Hello3Service?wsdl")
@HandlerChain(file="handlers.xml")
public class Hello3WsService
    extends Service
{

    private final static URL HELLO3WSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.lejingw.apps.ws31.Hello3WsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = com.lejingw.apps.ws31.Hello3WsService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8080/lstzsb/Hello3Service?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8080/lstzsb/Hello3Service?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        HELLO3WSSERVICE_WSDL_LOCATION = url;
    }

    public Hello3WsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Hello3WsService() {
        super(HELLO3WSSERVICE_WSDL_LOCATION, new QName("http://ws3.apps.lejingw.com", "Hello3WsService"));
    }

    /**
     * 
     * @return
     *     returns IHello3WsService
     */
    @WebEndpoint(name = "Hello3WsServicePort")
    public IHello3WsService getHello3WsServicePort() {
        return super.getPort(new QName("http://ws3.apps.lejingw.com", "Hello3WsServicePort"), IHello3WsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IHello3WsService
     */
    @WebEndpoint(name = "Hello3WsServicePort")
    public IHello3WsService getHello3WsServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws3.apps.lejingw.com", "Hello3WsServicePort"), IHello3WsService.class, features);
    }

}
