package com.totyu.apps.ws.hello4;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.totyu.apps.ws.vo.Customer;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-b02- Generated
 * source version: 2.1
 * 
 */
@WebService(name = "Hello4WsService", targetNamespace = "http://ws4.apps.lejingw.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Hello4Service {

	/**
	 * 
	 * @param customer
	 */
	@WebMethod
	public void uploadCustomerByName(
			@WebParam(name = "customer", partName = "customer") Customer customer);

}
