
package com.lejingw.apps.ws3;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IHello3WsService", targetNamespace = "http://ws3.apps.lejingw.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IHello3WsService {


    /**
     * 
     * @param name
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "str", targetNamespace = "http://ws3.apps.lejingw.com")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws3.apps.lejingw.com", className = "com.lejingw.apps.ws3.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws3.apps.lejingw.com", className = "com.lejingw.apps.ws3.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "name", targetNamespace = "http://ws3.apps.lejingw.com")
        String name);

    /**
     * 
     * @param limit
     * @param start
     * @return
     *     returns java.util.List<com.lejingw.apps.ws3.Pager>
     */
    @WebMethod
    @WebResult(name = "pager", targetNamespace = "http://ws3.apps.lejingw.com")
    @RequestWrapper(localName = "getPagerList", targetNamespace = "http://ws3.apps.lejingw.com", className = "com.lejingw.apps.ws3.GetPagerList")
    @ResponseWrapper(localName = "getPagerListResponse", targetNamespace = "http://ws3.apps.lejingw.com", className = "com.lejingw.apps.ws3.GetPagerListResponse")
    public List<Pager> getPagerList(
        @WebParam(name = "start", targetNamespace = "http://ws3.apps.lejingw.com")
        int start,
        @WebParam(name = "limit", targetNamespace = "http://ws3.apps.lejingw.com")
        int limit);

    /**
     * 
     * @param pager
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "str", targetNamespace = "http://ws3.apps.lejingw.com")
    @RequestWrapper(localName = "getPagerStr", targetNamespace = "http://ws3.apps.lejingw.com", className = "com.lejingw.apps.ws3.GetPagerStr")
    @ResponseWrapper(localName = "getPagerStrResponse", targetNamespace = "http://ws3.apps.lejingw.com", className = "com.lejingw.apps.ws3.GetPagerStrResponse")
    public String getPagerStr(
        @WebParam(name = "pager", targetNamespace = "http://ws3.apps.lejingw.com")
        Pager pager);

}
