
package com.lejingw.apps.ws2;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "Hello2WsService", targetNamespace = "http://ws2.apps.lejingw.com")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Hello2WsService {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.lejingw.apps.ws2.SayHelloResponse>
     */
    @WebMethod(operationName = "sayHello")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.SayHelloResponse")
    public Response<SayHelloResponse> sayHelloAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "sayHello")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.SayHelloResponse")
    public Future<?> sayHelloAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SayHelloResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.SayHelloResponse")
    public String sayHello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.lejingw.apps.ws2.GetPagerResponse>
     */
    @WebMethod(operationName = "getPager")
    @RequestWrapper(localName = "getPager", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPager")
    @ResponseWrapper(localName = "getPagerResponse", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerResponse")
    public Response<GetPagerResponse> getPagerAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPager")
    @RequestWrapper(localName = "getPager", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPager")
    @ResponseWrapper(localName = "getPagerResponse", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerResponse")
    public Future<?> getPagerAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetPagerResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.lejingw.apps.ws2.Pager
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPager", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPager")
    @ResponseWrapper(localName = "getPagerResponse", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerResponse")
    public Pager getPager(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.lejingw.apps.ws2.GetPagerStrResponse>
     */
    @WebMethod(operationName = "getPagerStr")
    @RequestWrapper(localName = "getPagerStr", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerStr")
    @ResponseWrapper(localName = "getPagerStrResponse", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerStrResponse")
    public Response<GetPagerStrResponse> getPagerStrAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Pager arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPagerStr")
    @RequestWrapper(localName = "getPagerStr", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerStr")
    @ResponseWrapper(localName = "getPagerStrResponse", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerStrResponse")
    public Future<?> getPagerStrAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Pager arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetPagerStrResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPagerStr", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerStr")
    @ResponseWrapper(localName = "getPagerStrResponse", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerStrResponse")
    public String getPagerStr(
        @WebParam(name = "arg0", targetNamespace = "")
        Pager arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.lejingw.apps.ws2.GetPagerListResponse>
     */
    @WebMethod(operationName = "getPagerList")
    @RequestWrapper(localName = "getPagerList", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerList")
    @ResponseWrapper(localName = "getPagerListResponse", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerListResponse")
    public Response<GetPagerListResponse> getPagerListAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Pager arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getPagerList")
    @RequestWrapper(localName = "getPagerList", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerList")
    @ResponseWrapper(localName = "getPagerListResponse", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerListResponse")
    public Future<?> getPagerListAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        Pager arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetPagerListResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.lejingw.apps.ws2.Pager>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPagerList", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerList")
    @ResponseWrapper(localName = "getPagerListResponse", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.GetPagerListResponse")
    public List<Pager> getPagerList(
        @WebParam(name = "arg0", targetNamespace = "")
        Pager arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.lejingw.apps.ws2.SavaPicData2Response>
     */
    @WebMethod(operationName = "savaPicData2")
    @RequestWrapper(localName = "savaPicData2", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.SavaPicData2")
    @ResponseWrapper(localName = "savaPicData2Response", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.SavaPicData2Response")
    public Response<SavaPicData2Response> savaPicData2Async(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "savaPicData2")
    @RequestWrapper(localName = "savaPicData2", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.SavaPicData2")
    @ResponseWrapper(localName = "savaPicData2Response", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.SavaPicData2Response")
    public Future<?> savaPicData2Async(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<SavaPicData2Response> asyncHandler);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "savaPicData2", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.SavaPicData2")
    @ResponseWrapper(localName = "savaPicData2Response", targetNamespace = "http://ws2.apps.lejingw.com", className = "com.lejingw.apps.ws2.SavaPicData2Response")
    public void savaPicData2(
        @WebParam(name = "arg0", targetNamespace = "")
        byte[] arg0);

}
