package com.lejingw.apps.ws4;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-b02- Generated
 * source version: 2.1
 * 
 */
@WebService(name = "Hello4WsService", targetNamespace = "http://ws4.apps.lejingw.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({ ObjectFactory.class })
public interface Hello4WsService {

	/**
	 * 
	 * @param customer
	 */
	@WebMethod
	public void uploadCustomerByName(
			@WebParam(name = "customer", partName = "customer") Customer customer);

}
