
package com.totyu.web.ws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-b02-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "tzsbServicePortType", targetNamespace = "http://localhost:88/scdeap/services")
public interface ZhongheWebServiceClient {


    /**
     * @param in2
     * @param in1
     * @param in4
     * @param in3
     * @param in0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "do_TzsbTranService")
    @WebResult(name = "out", targetNamespace = "http://localhost:88/scdeap/services")
    @RequestWrapper(localName = "do_TzsbTranService", targetNamespace = "http://localhost:88/scdeap/services")
    @ResponseWrapper(localName = "do_TzsbTranServiceResponse", targetNamespace = "http://localhost:88/scdeap/services")
    public String doTzsbTranService(
        @WebParam(name = "in0", targetNamespace = "http://localhost:88/scdeap/services")
        String in0,
        @WebParam(name = "in1", targetNamespace = "http://localhost:88/scdeap/services")
        String in1,
        @WebParam(name = "in2", targetNamespace = "http://localhost:88/scdeap/services")
        String in2,
        @WebParam(name = "in3", targetNamespace = "http://localhost:88/scdeap/services")
        String in3,
        @WebParam(name = "in4", targetNamespace = "http://localhost:88/scdeap/services")
        String in4);

}
